### PR TITLE
Add test cases for one side of Park on same line

### PR DESCRIPTION
**Pull request by cuprous**
--Add three new test cases, one for each MBTA line, that tests for
  stops that are on the same "side" of Park Street.

### CODE REVIEW

**Comment by RealWeeks** [comment]
Ah, I see why you close the last one.  But looks like you didn't include mbta.js on this.  Thanks for the test though, will consider adding to practice.

**Comment by RealWeeks** [comment]
Do not close. Consider incorporating bonus tests.

**Comment by jrhorn424** [comment]
Why wasn't this closed?

**Comment by jrhorn424** [comment]
@J-Weeks These were Jasmine tests?

**Comment by jrhorn424** [comment]
@cuprous Would you mind removing your solution from this PR and opening a different one targeting solution instead of master? Thanks.

**Comment by jrhorn424** [comment]
I still want to merge the tests. @cuprous

**Comment by cuprous** [comment]
@jrhorn424 

When do you need me to make the changes by? Busy with the group project, currently.

**Comment by cuprous** [comment]
@jrhorn424 

Closing pull request and resubmitting with solution removed and aimed at solution branch.

**Comment by jrhorn424** [comment]
@cuprous Thanks! It wasn't urgent. Sorry I just saw this. 😢

**Comment by gaand** [comment]
My mistake.  I missed this conversation.

**Pull request closed without merging**
