### PR TITLE
Bonus

### PR DESCRIPTION
**Pull request by soynog**
- Also updated tests to make sense for the bonus changes.

### CODE REVIEW

**Comment by RealWeeks** [comment]
YOU WROTE TESTS SOOOOOOOO AWESOME YOU WON MY HEART.  I'm, going to keep this open for a possible merge into the lesson!

Great job keep up the good work.

**Comment by RealWeeks** [comment]
Do not close.  Consider integrating test.

**Comment by jrhorn424** [comment]
@J-Weeks These were Jasmine tests?

**Comment by jrhorn424** [comment]
Since these are tests and solutions for a bonus, it needs to live on a separate branch. @soynog Would you please re-open another PR targeting the bonus branch I just pushed?

**Pull request closed without merging**
